---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-vault-plugin
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-vault-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-vault-plugin
subjects:
  - kind: ServiceAccount
    name: argocd
    namespace: argocd
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-oidc-secret
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "secret/data/argocd"
    avp.kubernetes.io/secret-version: "1"
type: Opaque
stringData:
  oidc.vault.clientSecret: <clientSecret>