---
# Let's Encrypt Staging Issuer (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@homelab.local
    privateKeySecretRef:
      name: letsencrypt-staging-private-key
    solvers:
    - dns01:
        cloudflare:
          email: admin@homelab.local
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
        - "homelab.local"
---
# Let's Encrypt Production Issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@homelab.local
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
    - dns01:
        cloudflare:
          email: admin@homelab.local
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
        - "homelab.local"
---
# Self-signed issuer for internal services
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# CA Issuer for internal PKI
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-key-pair
---
# Root CA Certificate for internal services
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-ca-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: Homelab Root CA
  secretName: ca-key-pair
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizationalUnits:
      - Infrastructure
    organizations:
      - Homelab
    countries:
      - UK
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# Wildcard certificate for homelab.local
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-homelab-local
  namespace: cert-manager
spec:
  secretName: wildcard-homelab-local-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.homelab.local"
    - "homelab.local"
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
---
# Certificate for ArgoCD
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-cert
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argocd.homelab.local
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days