---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: external-secrets
    repoURL: https://external-secrets.github.io/external-secrets/
    targetRevision: 0.9.11
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        replicaCount: 2
        
        # Enable leader election for HA
        leaderElect: true
        
        serviceMonitor:
          enabled: true
          namespace: monitoring
        
        # Webhook configuration for validation
        webhook:
          replicaCount: 2
          create: true
          serviceMonitor:
            enabled: true
        
        # Cert Controller for webhook certificates
        certController:
          replicaCount: 2
          create: true
          serviceMonitor:
            enabled: true
        
        # Resource limits and requests
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
            
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true