---
apiVersion: v1
kind: Secret
metadata:
  name: transmission-vpn-secret
  namespace: media
type: Opaque
data:
  # These will be populated by external-secrets from Vault
  vpn-username: ""
  vpn-password: ""
  vpn-config: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: media
data:
  settings.json: |
    {
      "alt-speed-down": 50,
      "alt-speed-enabled": false,
      "alt-speed-time-begin": 540,
      "alt-speed-time-day": 127,
      "alt-speed-time-enabled": false,
      "alt-speed-time-end": 1020,
      "alt-speed-up": 50,
      "bind-address-ipv4": "0.0.0.0",
      "bind-address-ipv6": "::",
      "blocklist-enabled": true,
      "blocklist-url": "https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz",
      "cache-size-mb": 4,
      "dht-enabled": true,
      "download-dir": "/downloads/complete",
      "download-queue-enabled": true,
      "download-queue-size": 10,
      "encryption": 1,
      "idle-seeding-limit": 30,
      "idle-seeding-limit-enabled": false,
      "incomplete-dir": "/downloads/incomplete",
      "incomplete-dir-enabled": true,
      "lpd-enabled": false,
      "message-level": 2,
      "peer-congestion-algorithm": "",
      "peer-id-ttl-hours": 6,
      "peer-limit-global": 200,
      "peer-limit-per-torrent": 50,
      "peer-port": 51413,
      "peer-port-random-high": 65535,
      "peer-port-random-low": 49152,
      "peer-port-random-on-start": false,
      "peer-socket-tos": "default",
      "pex-enabled": true,
      "port-forwarding-enabled": true,
      "preallocation": 1,
      "prefetch-enabled": true,
      "queue-stalled-enabled": true,
      "queue-stalled-minutes": 30,
      "ratio-limit": 2,
      "ratio-limit-enabled": false,
      "rename-partial-files": true,
      "rpc-authentication-required": false,
      "rpc-bind-address": "0.0.0.0",
      "rpc-enabled": true,
      "rpc-host-whitelist": "",
      "rpc-host-whitelist-enabled": false,
      "rpc-password": "",
      "rpc-port": 9091,
      "rpc-url": "/transmission/",
      "rpc-username": "",
      "rpc-whitelist": "",
      "rpc-whitelist-enabled": false,
      "scrape-paused-torrents-enabled": true,
      "script-torrent-done-enabled": false,
      "script-torrent-done-filename": "",
      "seed-queue-enabled": false,
      "seed-queue-size": 10,
      "speed-limit-down": 100,
      "speed-limit-down-enabled": false,
      "speed-limit-up": 100,
      "speed-limit-up-enabled": false,
      "start-added-torrents": true,
      "trash-original-torrent-files": false,
      "umask": 18,
      "upload-slots-per-torrent": 14,
      "utp-enabled": true,
      "watch-dir": "/downloads/watch",
      "watch-dir-enabled": true
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-vpn
  namespace: media
  labels:
    app: transmission-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission-vpn
  template:
    metadata:
      labels:
        app: transmission-vpn
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: false  # VPN requires root for network setup
        runAsUser: 0
      containers:
      - name: transmission-vpn
        image: haugene/transmission-openvpn:latest
        ports:
        - containerPort: 9091
          name: http
        - containerPort: 51413
          name: peer-tcp
          protocol: TCP
        - containerPort: 51413
          name: peer-udp
          protocol: UDP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/London"
        - name: OPENVPN_PROVIDER
          value: "NORDVPN"
        - name: OPENVPN_CONFIG
          value: "uk1785,uk1786,uk1787"
        - name: OPENVPN_USERNAME
          valueFrom:
            secretKeyRef:
              name: transmission-vpn-secret
              key: vpn-username
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transmission-vpn-secret
              key: vpn-password
        - name: LOCAL_NETWORK
          value: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
        - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
          value: "false"
        - name: TRANSMISSION_RPC_HOST_WHITELIST_ENABLED
          value: "false"
        - name: TRANSMISSION_RPC_WHITELIST_ENABLED
          value: "false"
        - name: TRANSMISSION_DOWNLOAD_DIR
          value: "/downloads/complete"
        - name: TRANSMISSION_INCOMPLETE_DIR
          value: "/downloads/incomplete"
        - name: TRANSMISSION_WATCH_DIR
          value: "/downloads/watch"
        - name: TRANSMISSION_DOWNLOAD_QUEUE_SIZE
          value: "10"
        - name: TRANSMISSION_SPEED_LIMIT_UP_ENABLED
          value: "true"
        - name: TRANSMISSION_SPEED_LIMIT_UP
          value: "100"
        - name: ENABLE_UFW
          value: "false"
        - name: UFW_ALLOW_GW_NET
          value: "false"
        - name: UFW_EXTRA_PORTS
          value: ""
        - name: UFW_DISABLE_IPTABLES_REJECT
          value: "false"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        - name: transmission-settings
          mountPath: /config/transmission-home/settings.json
          subPath: settings.json
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 2Gi
            cpu: 1000m
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        livenessProbe:
          httpGet:
            path: /transmission/web/
            port: 9091
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /transmission/web/
            port: 9091
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: transmission-config-pvc
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-pvc
      - name: transmission-settings
        configMap:
          name: transmission-config
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: media
  labels:
    app: transmission-vpn
spec:
  selector:
    app: transmission-vpn
  ports:
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission-ingress
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: media-transmission-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - transmission.shreck.co.uk
    secretName: transmission-tls
  rules:
  - host: transmission.shreck.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: transmission
            port:
              number: 9091
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: transmission-auth
  namespace: media
spec:
  basicAuth:
    secret: transmission-auth-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: transmission-auth-secret
  namespace: media
type: Opaque
data:
  # admin:$2y$10$... (bcrypt hash of password)
  users: YWRtaW46JDJ5JDEwJE5JWDB2RjBGL01ZTGFOR0JIcUkwMU9lWFhZQVJOSE5wRjNHWUJFRkw2WnZBWWY2NDZNaTZL