---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Ti
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  nfs:
    server: 10.10.1.100  # NFS server IP
    path: /mnt/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 2Ti
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-downloads
  nfs:
    server: 10.10.1.100
    path: /mnt/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-downloads
  resources:
    requests:
      storage: 2Ti
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-downloads
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: ssd