---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tv-pv
  labels:
    type: nfs-fast-ssd
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-fast-ssd
  nfs:
    server: 10.10.0.178  # Proxmox host IP
    path: /fast-ssd/media/tv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-fast-ssd
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-pv
  labels:
    type: nfs-fast-ssd
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-fast-ssd
  nfs:
    server: 10.10.0.178
    path: /fast-ssd/media/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-fast-ssd
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-pv
  labels:
    type: nfs-fast-ssd
spec:
  capacity:
    storage: 80Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-fast-ssd
  nfs:
    server: 10.10.0.178
    path: /fast-ssd/media/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-fast-ssd
  resources:
    requests:
      storage: 80Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-music-pv
  labels:
    type: nfs-fast-ssd
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-fast-ssd
  nfs:
    server: 10.10.0.178
    path: /fast-ssd/media/music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-fast-ssd
  resources:
    requests:
      storage: 20Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-fast-ssd
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer