---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-namespace
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaz-mi6/homelab-ops.git
    targetRevision: HEAD
    path: infrastructure/k8s/media/namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-storage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaz-mi6/homelab-ops.git
    targetRevision: HEAD
    path: infrastructure/k8s/media/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
  - name: Description
    value: "NFS storage configuration for media library and downloads"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaz-mi6/homelab-ops.git
    targetRevision: HEAD
    path: infrastructure/k8s/media/sonarr
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
  - name: Description
    value: "TV series management and automated downloading"
  - name: URL
    value: "https://sonarr.shreck.co.uk"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaz-mi6/homelab-ops.git
    targetRevision: HEAD
    path: infrastructure/k8s/media/radarr
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
  - name: Description
    value: "Movie management and automated downloading"
  - name: URL
    value: "https://radarr.shreck.co.uk"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaz-mi6/homelab-ops.git
    targetRevision: HEAD
    path: infrastructure/k8s/media/prowlarr
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
  - name: Description
    value: "Centralized indexer management for Sonarr and Radarr"
  - name: URL
    value: "https://prowlarr.shreck.co.uk"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cleanuparr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaz-mi6/homelab-ops.git
    targetRevision: HEAD
    path: infrastructure/k8s/media/cleanuparr
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
  - name: Description
    value: "Automated media library maintenance and cleanup"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaz-mi6/homelab-ops.git
    targetRevision: HEAD
    path: infrastructure/k8s/media/transmission
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
  - name: Description
    value: "BitTorrent client with VPN integration"
  - name: URL
    value: "https://transmission.shreck.co.uk"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaz-mi6/homelab-ops.git
    targetRevision: HEAD
    path: infrastructure/k8s/media/plex
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
  - name: Description
    value: "Media server with hardware-accelerated transcoding"
  - name: URL
    value: "https://plex.shreck.co.uk"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-backup
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaz-mi6/homelab-ops.git
    targetRevision: HEAD
    path: infrastructure/k8s/media/backup
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
  - name: Description
    value: "Automated backup system for media configurations and databases"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaz-mi6/homelab-ops.git
    targetRevision: HEAD
    path: infrastructure/k8s/media/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
  - name: Description
    value: "Monitoring dashboards and metrics collection for media stack"