---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: infrastructure
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 25.0.0
    helm:
      releaseName: traefik
      values: |
        # Deployment configuration
        deployment:
          replicas: 2
          
        # Enable HA with leader election
        cluster:
          store: etcd
          prefix: traefik
          
        # Configure ports and entrypoints
        ports:
          web:
            port: 8000
            expose: true
            exposedPort: 80
            protocol: TCP
            redirectTo: websecure
          websecure:
            port: 8443
            expose: true
            exposedPort: 443
            protocol: TCP
            tls:
              enabled: true
              options: "modern@file"
          traefik:
            port: 9000
            expose: true
            exposedPort: 9000
            protocol: TCP
          metrics:
            port: 9100
            expose: false
            protocol: TCP
            
        # TLS Configuration
        tlsOptions:
          modern:
            sslProtocols:
              - "TLSv1.2"
              - "TLSv1.3"
            cipherSuites:
              - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
              - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
              - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
            clientAuth:
              clientAuthType: RequestClientCert
              
        # Enable API and Dashboard
        api:
          dashboard: true
          insecure: false
          
        # Certificate resolvers for Let's Encrypt
        certificatesResolvers:
          letsencrypt:
            acme:
              email: admin@homelab.local
              storage: /data/acme.json
              caServer: https://acme-v02.api.letsencrypt.org/directory
              dnsChallenge:
                provider: cloudflare
                resolvers:
                  - "1.1.1.1:53"
                  - "1.0.0.1:53"
                delayBeforeCheck: 10
          letsencrypt-staging:
            acme:
              email: admin@homelab.local
              storage: /data/acme-staging.json
              caServer: https://acme-staging-v02.api.letsencrypt.org/directory
              dnsChallenge:
                provider: cloudflare
                resolvers:
                  - "1.1.1.1:53"
                  - "1.0.0.1:53"
                delayBeforeCheck: 10
                
        # Environment variables for Cloudflare
        env:
          - name: CF_DNS_API_TOKEN
            valueFrom:
              secretKeyRef:
                key: api-token
                name: cloudflare-api-token-secret
                
        # Persistence for ACME certificates
        persistence:
          enabled: true
          name: data
          accessMode: ReadWriteOnce
          size: 128Mi
          storageClass: local-path
          path: /data
          annotations: {}
          
        # Service configuration
        service:
          enabled: true
          type: LoadBalancer
          annotations:
            metallb.universe.tf/allow-shared-ip: traefik
          spec:
            loadBalancerIP: 10.10.1.100
            externalTrafficPolicy: Local
            
        # Metrics and monitoring
        metrics:
          prometheus:
            addEntryPointsLabels: true
            addServicesLabels: true
            addRoutersLabels: true
            service:
              enabled: true
            serviceMonitor:
              enabled: true
              namespace: monitoring
              
        # Logging configuration
        logs:
          general:
            level: INFO
          access:
            enabled: true
            format: json
            
        # Additional arguments
        additionalArguments:
          - "--serverstransport.insecureskipverify=true"
          - "--ping=true"
          - "--ping.entrypoint=traefik"
          - "--entrypoints.web.address=:8000/tcp"
          - "--entrypoints.websecure.address=:8443/tcp"
          - "--entrypoints.traefik.address=:9000/tcp"
          - "--entrypoints.metrics.address=:9100/tcp"
          - "--metrics.prometheus=true"
          - "--metrics.prometheus.addEntryPointsLabels=true"
          - "--metrics.prometheus.addServicesLabels=true"
          - "--metrics.prometheus.addRoutersLabels=true"
          - "--metrics.prometheus.entryPoint=metrics"
          - "--providers.kubernetescrd.allowCrossNamespace=true"
          - "--providers.kubernetescrd.allowExternalNameServices=true"
          - "--providers.kubernetesingress.allowExternalNameServices=true"
          
        # Security context
        securityContext:
          capabilities:
            drop: [ALL]
            add: [NET_BIND_SERVICE]
          readOnlyRootFilesystem: true
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
          
        # Pod security context
        podSecurityContext:
          fsGroup: 65532
          
        # Resources
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "300m"
            memory: "150Mi"
            
        # Node selector for dedicated nodes
        # nodeSelector:
        #   node-role.kubernetes.io/worker: "true"
          
        # Pod disruption budget
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
          
        # Horizontal Pod Autoscaler
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 5
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 70
          - type: Resource
            resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true