---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.homelab.local:587'
      smtp_from: 'alertmanager@homelab.local'
      smtp_auth_username: 'alertmanager@homelab.local'
      smtp_auth_password: 'smtp_password_from_vault'
      slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
      resolve_timeout: 5m
      
    templates:
      - '/etc/alertmanager/templates/*.tmpl'
      
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'web.hook'
      routes:
        # Critical alerts - immediate notification
        - match:
            severity: critical
          receiver: critical-alerts
          group_wait: 0s
          group_interval: 5m
          repeat_interval: 30m
          
        # Infrastructure alerts
        - match:
            team: infrastructure
          receiver: infrastructure-team
          group_interval: 5m
          repeat_interval: 2h
          
        # Platform alerts
        - match:
            team: platform
          receiver: platform-team
          group_interval: 5m
          repeat_interval: 2h
          
        # Security alerts
        - match:
            alertname: SecurityAlert
          receiver: security-team
          group_wait: 0s
          group_interval: 1m
          repeat_interval: 15m
          
        # Silenced alerts during maintenance
        - match:
            maintenance: "true"
          receiver: 'null'
          
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']
        
    receivers:
      - name: 'web.hook'
        webhook_configs:
          - url: 'http://alertmanager-webhook.monitoring.svc.cluster.local:9093/webhook'
            send_resolved: true
            http_config:
              follow_redirects: true
            
      - name: critical-alerts
        email_configs:
          - to: 'admin@homelab.local'
            subject: 'CRITICAL: {{ template "email.default.subject" . }}'
            body: |
              {{ template "email.default.html" . }}
            headers:
              X-Priority: '1'
              X-MSMail-Priority: 'High'
        slack_configs:
          - channel: '#alerts-critical'
            color: 'danger'
            title: 'Critical Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
            text: |
              {{ range .Alerts }}
              *Environment:* {{ .Labels.cluster }}
              *Severity:* {{ .Labels.severity }}
              *Description:* {{ .Annotations.description }}
              *Runbook:* {{ .Annotations.runbook_url }}
              {{ end }}
        webhook_configs:
          - url: 'https://api.pagerduty.com/generic/2010-04-15/create_event.json'
            send_resolved: true
            http_config:
              follow_redirects: true
            
      - name: infrastructure-team
        email_configs:
          - to: 'infrastructure@homelab.local'
            subject: 'Infrastructure Alert: {{ template "email.default.subject" . }}'
            body: |
              {{ template "email.default.html" . }}
        slack_configs:
          - channel: '#infrastructure'
            color: 'warning'
            title: 'Infrastructure Alert'
            text: |
              {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Severity:* {{ .Labels.severity }}
              {{ end }}
              
      - name: platform-team
        email_configs:
          - to: 'platform@homelab.local'
            subject: 'Platform Alert: {{ template "email.default.subject" . }}'
            body: |
              {{ template "email.default.html" . }}
        slack_configs:
          - channel: '#platform'
            color: 'warning'
            title: 'Platform Alert'
            text: |
              {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              {{ end }}
              
      - name: security-team
        email_configs:
          - to: 'security@homelab.local'
            subject: 'SECURITY ALERT: {{ template "email.default.subject" . }}'
            body: |
              {{ template "email.default.html" . }}
            headers:
              X-Priority: '1'
              X-MSMail-Priority: 'High'
        slack_configs:
          - channel: '#security-alerts'
            color: 'danger'
            title: 'Security Alert'
            text: |
              {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              *Source:* {{ .Labels.instance }}
              *Time:* {{ .StartsAt }}
              {{ end }}
              
      - name: 'null'
        # Silent receiver for maintenance mode
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  default.tmpl: |
    {{ define "email.default.subject" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }}
    {{ end }}
    
    {{ define "email.default.html" }}
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        .header { background: #1f77b4; color: white; padding: 10px; }
        .alert { margin: 10px 0; padding: 10px; border-left: 4px solid #1f77b4; }
        .firing { border-left-color: #d62728; }
        .resolved { border-left-color: #2ca02c; }
        .critical { border-left-color: #ff7f0e; }
        .warning { border-left-color: #ffbb78; }
      </style>
    </head>
    <body>
      <div class="header">
        <h2>AlertManager Notification</h2>
        <p>Cluster: {{ .CommonLabels.cluster }}</p>
        <p>Status: {{ .Status | title }}</p>
      </div>
      
      {{ range .Alerts }}
      <div class="alert {{ .Status }}{{ if .Labels.severity }} {{ .Labels.severity }}{{ end }}">
        <h3>{{ .Annotations.summary }}</h3>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        <p><strong>Labels:</strong>
        {{ range .Labels.SortedPairs }}
          {{ .Name }}: {{ .Value }}<br>
        {{ end }}
        </p>
        <p><strong>Started:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}</p>
        {{ if .EndsAt }}
        <p><strong>Ended:</strong> {{ .EndsAt.Format "2006-01-02 15:04:05 UTC" }}</p>
        {{ end }}
        {{ if .Annotations.runbook_url }}
        <p><strong>Runbook:</strong> <a href="{{ .Annotations.runbook_url }}">{{ .Annotations.runbook_url }}</a></p>
        {{ end }}
      </div>
      {{ end }}
    </body>
    </html>
    {{ end }}